### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by luminosity-design** [katoni/php-ffx#1]
Hi, firstly thanks for porting this. Not sure if you are still updating?

On PHP 8.1, there is a deprecation warning

`Deprecated: Implicit conversion from float 2.5 to int loses precision in vendor\katoni\php-ffx\src\FFX.php on line 68`
`Deprecated: Implicit conversion from float 2.5 to int loses precision in vendor\katoni\php-ffx\src\FFX.php on line 69`

It seems to be caused by the casting wasn't properly enclosed in brackets on line 65. Changing it to the following fixes the problem:
`$s = (int) (count($v) / 2);`

**Comment by mpskovvang** [comment]
Thanks for reporting. I've pushed a new release.
